/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 itachi.glb --transform 
Files: itachi.glb [2.18MB] > C:\Users\iagoc\OneDrive\Desktop\Programação\sherk_treino\src\assets\itachi-transformed.glb [225.78KB] (90%)
Author: angelolamonaca (https://sketchfab.com/angelolamonaca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/itachi-uchiha-sharingan-akatsuki-amaterasu-867dfc95e96a49878837f80428918ca9
Title: Itachi Uchiha Sharingan Akatsuki Amaterasu
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/itachi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Suit} position={[0.002, 0.143, 0.002]} scale={0.368} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} position={[0.002, 0.143, 0.002]} scale={0.368} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Ears} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14_2" geometry={nodes.mesh_14_2.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14_2.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14_2.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14_3" geometry={nodes.mesh_14_3.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14_3.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14_3.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14_4" geometry={nodes.mesh_14_4.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14_4.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14_4.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14_5" geometry={nodes.mesh_14_5.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14_5.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14_5.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14" geometry={nodes.mesh_14.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
      <mesh name="mesh_14_1" geometry={nodes.mesh_14_1.geometry} material={materials.PaletteMaterial001} morphTargetDictionary={nodes.mesh_14_1.morphTargetDictionary} morphTargetInfluences={nodes.mesh_14_1.morphTargetInfluences} position={[-0.002, 0.692, 0.037]} scale={0.052} />
    </group>
  )
}

useGLTF.preload('/itachi-transformed.glb')
