/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 personagem.glb --transform 
Files: personagem.glb [8.92MB] > C:\Users\iagoc\OneDrive\Desktop\Programação\sherk_treino\src\assets\personagem-transformed.glb [1.31MB] (85%)
Author: fredbear1211 (https://sketchfab.com/fredbear1211)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shrek-walk-cycle-cd5a1e1cd7dd4effa3df11bcaea915f4
Title: Shrek Walk Cycle
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/personagem-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.eyeball_r} skeleton={nodes.Object_18.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.eyeball_r} skeleton={nodes.Object_19.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
        <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['ShrekBody.001']} skeleton={nodes.Object_20.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.ShrekHead} skeleton={nodes.Object_21.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
        <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Material} skeleton={nodes.Object_23.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
        <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.ShrekBody} skeleton={nodes.Object_24.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      </group>
    </group>
  )
}

useGLTF.preload('/personagem-transformed.glb')
