/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 pikachu.glb --transform 
Files: pikachu.glb [304.59KB] > C:\Users\iagoc\OneDrive\Desktop\Programação\sherk_treino\src\assets\pikachu-transformed.glb [60.45KB] (80%)
Author: jacobjksn42 (https://sketchfab.com/jacobjksn42)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pikachu-c22dab8fc3064c76a0c502d64555a74f
Title: Pikachu
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pikachu-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Material_160} skeleton={nodes.Object_6.skeleton} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material_161} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Material_162} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Material_163} skeleton={nodes.Object_9.skeleton} />
    </group>
  )
}

useGLTF.preload('/pikachu-transformed.glb')
