/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 shrekModelo.glb --transform 
Files: shrekModelo.glb [6.15MB] > C:\Users\iagoc\OneDrive\Desktop\Programação\sherk_treino\src\assets\shrekModelo-transformed.glb [741.94KB] (88%)
*/

import React, { useRef , useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useAnimationContext } from './context/AnimationProvider.jsx'

export function Model(props) {

  const {animationState} = useAnimationContext();


  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/shrekModelo-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions) {
      actions[animationState].reset().fadeIn(0.1).play()
      return () => actions[animationState].fadeOut(0.3)
    }
  }, [actions, animationState])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="main" rotation={[-Math.PI / 2, 0, 0]} scale={0.039}>
          <primitive object={nodes.ValveBipedBip01_Pelvis} />
        </group>
        <directionalLight name="DirectionalLight" intensity={2.08} decay={2} position={[-1.822, 2.063, 7.5]}>
          <group position={[0, 0, -1]} />
        </directionalLight>
        <directionalLight name="DirectionalLight_2" intensity={1} decay={2} position={[0.825, 2.97, -5.706]}>
          <group position={[0, 0, -1]} />
        </directionalLight>
        <skinnedMesh name="Body_1" geometry={nodes.Body_1.geometry} material={materials['Material.001']} skeleton={nodes.Body_1.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
        <skinnedMesh name="Body_2" geometry={nodes.Body_2.geometry} material={materials['Material.001']} skeleton={nodes.Body_2.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
        <skinnedMesh name="head_1" geometry={nodes.head_1.geometry} material={materials.eyeball_r} skeleton={nodes.head_1.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
        <skinnedMesh name="head_2" geometry={nodes.head_2.geometry} material={materials.eyeball_r} skeleton={nodes.head_2.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
        <skinnedMesh name="head_3" geometry={nodes.head_3.geometry} material={materials['Material.001']} skeleton={nodes.head_3.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
        <skinnedMesh name="head_4" geometry={nodes.head_4.geometry} material={materials.ShrekHead} skeleton={nodes.head_4.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={0.039} />
      </group>
    </group>
  )
}

useGLTF.preload('/shrekModelo-transformed.glb')
