/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 simba.glb --transform 
Files: simba.glb [181.32KB] > C:\Users\iagoc\OneDrive\Desktop\Programação\sherk_treino\src\assets\simba-transformed.glb [31.54KB] (83%)
Author: badanon1 (https://sketchfab.com/badanon1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/young-simba-d944bfa696014fd0b1301e83a31226e0
Title: Young Simba
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/simba-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['default_material_texture000.png']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/simba-transformed.glb')
